apiVersion: v1
kind: Service
metadata:
  name: chainlit-service
spec:
  type: NodePort
  selector:
    app: chainlit-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30090